<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <!-- gRPC -->
  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.59.0" />
    <PackageReference Include="Google.Protobuf" Version="3.25.0" />
    <PackageReference Include="Grpc.Tools" Version="2.59.0" PrivateAssets="all" />
  </ItemGroup>

  <!-- Entity Framework Core + PostgreSQL -->
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="7.0.13" PrivateAssets="all" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="7.0.11" />
  </ItemGroup>

  <!-- Redis -->
  <ItemGroup>
    <PackageReference Include="StackExchange.Redis" Version="2.6.122" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>

  <!-- Protobuf -->
  <ItemGroup>
    <Protobuf Include="..\Proto\stats.proto" GrpcServices="Server" Link="Protos\stats.proto" />
  </ItemGroup>
</Project>